name: uaedialer
description: UAE dialer helps to call india and other countries for low call rate.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  contacts_service: any
  camera: ^0.2.1
  shared_preferences: 0.4.2
  contact_picker: ^0.0.2
  sqflite : any
  url_launcher: ^3.0.3
  path_provider: ^0.4.1
  splashscreen: ^1.1.0
  flutter_launcher_icons: "^0.6.1"
  # firebase_messaging: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter_icons:
  android: true 
  ios: true
  image_path: "icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/icon/icon-foreground.png"    

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/images/ic_grass.png
   - assets/images/logo.png
   - assets/country_codes.json
   - assets/images/dc-short-logo.png
   - assets/images/app_logo.png


  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
          weight: 600
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 600
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600    
    - family: Nunito-Light
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 600    
    - family: Nunito-Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 600  

